spring:
  application:
    name: driveindex
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:/flyway