spring:
  application:
    name: driveindex
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:/flyway