spring:
  application:
    name: driveindex
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true
vaadin:
  bun:
    enable: true
